Update [dbo].[Products] Set ProductName = 'Gustaf''s Knäckebröd' Where ProductId = 22;
Update [dbo].[Products] Set ProductName = 'Tunnbröd' Where ProductId = 23;
Update [dbo].[Products] Set ProductName = 'Guaraná Fantástica' Where ProductId = 24;
Update [dbo].[Products] Set ProductName = 'NuNuCa Nuß-Nougat-Creme' Where ProductId = 25;
Update [dbo].[Products] Set ProductName = 'Gumbär Gummibärchen' Where ProductId = 26;
Update [dbo].[Products] Set ProductName = 'Rössle Sauerkraut' Where ProductId = 28;
Update [dbo].[Products] Set ProductName = 'Thüringer Rostbratwurst' Where ProductId = 29;
Update [dbo].[Products] Set ProductName = 'Côte de Blaye' Where ProductId = 38;
Update [dbo].[Products] Set ProductName = 'Tourtière' Where ProductId = 54;
Update [dbo].[Products] Set ProductName = 'Pâté chinois' Where ProductId = 55;
Update [dbo].[Products] Set ProductName = 'Sirop d''érable' Where ProductId = 61;
Update [dbo].[Products] Set ProductName = 'Wimmers gute Semmelknödel' Where ProductId = 64;
Update [dbo].[Products] Set ProductName = 'Röd Kaviar' Where ProductId = 73;
Update [dbo].[Products] Set ProductName = 'Rhönbräu Klosterbier' Where ProductId = 75;
Update [dbo].[Products] Set ProductName = 'Lakkalikööri' Where ProductId = 76;
Update [dbo].[Products] Set ProductName = 'Original Frankfurter grüne Soße' Where ProductId = 77;