-- Discounts
SET IDENTITY_INSERT [dbo].[Discounts] ON

-- discount expired yesterday
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (1, 3333, DATEADD(day, -41, GETDATE()), DATEADD(day, -1, GETDATE()), 3, CAST(0.250 AS Decimal(5, 3)), N'Get some Syrup', N'DO NOT MISS this deal on Aniseed Syrup. Where else are you going to find it for 25% off? NO WHERE!')	
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (2, 3434, DATEADD(day, -41, GETDATE()), DATEADD(day, -1, GETDATE()), 34, CAST(0.100 AS Decimal(5, 3)), N'10% Savings', N'Save 10% on Sasquatch Ale. This deal will not last long! ORDER IMMEDIATELY!')

-- discount started yesterday
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (3, 4444, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 4, CAST(0.125 AS Decimal(5, 3)), N'Tis the Seasoning', N'Order today! Save 12.5% on Chef Anton''s Italian Seasoning. You don''t want to make Chef Anton mad, do you?')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (4, 1515, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 15, CAST(0.100 AS Decimal(5, 3)), N'Go Green', N'Genen Shouyu goes on sale very rarely. Order now to save 10% off our already low price.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (5, 2727, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 27, CAST(0.500 AS Decimal(5, 3)), N'Half Price', N'Just because you can''t pronounce "Schoggi Schokolade" doesn''t mean you shouldn''t buy it. Get it now for 50% off!')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (6, 7777, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 7, CAST(0.150 AS Decimal(5, 3)), N'Pears for You', N'Bob''s Organic Pears are 15% off. You better buy as many as you can fit in your car!')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (7, 4040, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 40, CAST(0.300 AS Decimal(5, 3)), N'Don''t be Crabby', N'You have no reason to be crabby since Boston Crab Meat is 30% off.')

INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (8, 4400, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 44, CAST(0.250 AS Decimal(5, 3)), N'Gula Malacca Deal', N'You really should buy as many bags of Gula Malacca as you can fit in your kitchen.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (9, 4900, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 49, CAST(0.100 AS Decimal(5, 3)), N'Maxilaku Savings', N'Maximize your Maxilaku savings with this 10% discount.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (10, 5700, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 57, CAST(0.150 AS Decimal(5, 3)), N'Holy Ravioli!', N'Take advantage of this deal on raviolis today.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (11, 6200, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 62, CAST(0.300 AS Decimal(5, 3)), N'Pie Day', N'Did someone say French Canadian Sugar Pie is 30% off?')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (12, 6300, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 63, CAST(0.400 AS Decimal(5, 3)), N'Spread on the Savings', N'You have to eat your vegetables somehow. You might as well save some money while you do it.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (13, 6500, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 65, CAST(0.250 AS Decimal(5, 3)), N'Fiery Hot Savings', N'This is a red-hot deal on Fiery Hot Pepper Sauce. You better hurry before these savings are extinguished.')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (14, 6900, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 69, CAST(0.120 AS Decimal(5, 3)), N'No Joke', N'Laughing Lumberjack Lager is on sale today. This IS a laughing matter!')
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (15, 7300, DATEADD(day, -1, GETDATE()), DATEADD(day, 40, GETDATE()), 73, CAST(0.050 AS Decimal(5, 3)), N'The Finest Savings', N'Save today on our finest caviar.')

-- discount starts 1 week from today
INSERT INTO [dbo].[Discounts] ([DiscountID], [Code], [StartTime], [EndTime], [ProductID], [DiscountPercent], [Title], [Description]) VALUES (16, 1111, DATEADD(day, 7, GETDATE()), DATEADD(day, 47, GETDATE()), 1, CAST(0.250 AS Decimal(5, 3)), N'Chai Tea Blowout', N'For a limited time only, Northwind is offering a 25% discount on Chai Tea. Order today while supplies last!')

SET IDENTITY_INSERT [dbo].[Discounts] OFF
